version: "3"

services:
  hub-db:
    image: postgres:9.5@sha256:ee604a9025ec864da512736f765ae714112a77ffc39d762c76b67ca0f8597e9e
    container_name: jupyterhub-db
    restart: always
    env_file:
      - shared.env
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      - internal

  hub:
    depends_on:
      - hub-db
    image: materialdigital/pyiron-jhub:2021-06-08@sha256:10c188ff40f546a08de523c87e1cacea55b18c52ed0c1619489c9f2bafc04b79
    restart: always
    container_name: jupyterhub
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "data:/data"
    links:
      - hub-db
    env_file:
      - shared.env
      - pyiron.env
    environment:
      POSTGRES_HOST: hub-db
    command: /bin/bash -c "jupyterhub -f /srv/jupyterhub/jupyterhub_config.py && jupyterhub upgrade-db"
    networks:
      - internal
      - proxy-net

microservice_dbdocker:
    build: ./microservice_dbdocker
    depends_on:
      - mongodb
    #restart: always
    command: gunicorn -w 1 --timeout 120 -b :27777 wsgi:microservice
    ports:
      - "${EXTERNAL_IP:-127.0.0.1}:27777:27777"
    networks:
      - default
  mongodb:
    image: mongo:4.2
    #restart: always
    command: mongod --dbpath /data/db
    volumes:
      - dbdocker:/data/db
    #ports:
    #  - "${EXTERNAL_IP:-127.0.0.1}:27018:27017"
    networks:
      - default

volumes:
  data:
      name: jupyterhub-data
      driver: local
  db:
      name: jupyterhub-db-data
      driver: local

networks:
  proxy-net:
    external: true
    name: pmd-reverse-proxy-net
  internal:
    name: jupyterhub-network
